version: '3.1'
services:
    php-apache:
        build:
            context: ./
            dockerfile: .docker/php-apache/Dockerfile
        container_name: php-apache
        ports:
            - "8080:80"
        links:
            - mailhog
        volumes:
            - ./dist:/var/www/html:delegated
            - .docker/php-apache/logs/apache:/var/log/apache2:delegated
            - .docker/php-apache/logs/php:/usr/local/etc/php/log:delegated

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        ports:
            - "8082:8025"

    frontend:
        build:
            context: ./
            dockerfile: .docker/frontend/Dockerfile
        container_name: frontend
        working_dir: /home/node/app
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/home/node/app:delegated
        command: sh -c "npm i && npm start"